FROM tomcat:8.0
EXPOSE 8080
WORKDIR /tmp
RUN apt update && apt install -y default-jdk git maven && \
    git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
WORKDIR /tmp/boxfuse-sample-java-war-hello/
RUN mvn package
RUN cp /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/local/tomcat/webapps/
